#!/bin/sh
while read file
do
        case "$1" in
        "C-d")
                trash-put "$file" ;;
        "C-u")
                mv "$file" ../ ;;
        "C-a")
                mv "$file" ~/images/wallpapers/active/ ;;
        "C-i")
                mv "$file" ~/images/ ;;
        "C-p")
                mv "$file" /mnt/blue/.pr0n/ ;;
        "C-r")
                convert -rotate 90 "$file" "$file" ;;
        "C-c")
                echo -n "$file" | xclip -selection clipboard ;;
        "C-w")
                nitrogen --save --set-zoom-fill "$file" ;;
        "C-e")  
                gimp "$file" ;;
        esac
done

